### ISSUE TITLE
Running out of memory during model inference: inference/memory 

### ISSUE THREAD

**Issue by Michal-Muszynski** [IBM/terratorch#119]
**Describe the issue**
There is an issue of memory allocation by terratorch during running model inference on images (3600x3600 pixels)

**To Reproduce (optional, but appreciated)**
1. Run a ccc job:
with v100 and -mem 64g 
2. Select branch: git checkout cli/predict_bands
3. run inference:
![image](https://github.com/user-attachments/assets/fc2c6aec-92c2-4322-b037-23c886835112)
4. See error:
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 6.39 GiB. GPU 0 has a total capacty of 31.74 GiB of which 2.39 GiB is free. Including non-PyTorch memory, this process has 29.35 GiB memory in use. Of the allocated memory 22.61 GiB is allocated by PyTorch, and 6.36 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

--------------------------------- Update-------------------------
@romeokienzler @Joao-L-S-Almeida @paolo-fraccaro 
I have tried again to run inference on large tiles (3600x3600), using the same ccc settings (please see the 3rd point above), input tiles, v100, but version 0.99.7 of Terratorch. The error is the following:
"RuntimeError: Error(s) in loading state_dict for PixelwiseRegressionTask."
I think the issue is related to class PixelwiseRegressionTask and breaks ccc jobs before event starting memory allocation.

**Comment by Michal-Muszynski** [comment]
The memory allocation issue can be addressed by changing the size of sliding windows for inference (i.e., `tiled_inference_parameters`: `h_crop`, `h_stride`, `w_crop` in config files)

**Comment by romeokienzler** [comment]
@Michal-Muszynski available version 0.99.0, 0.99.1, 0.99.2, 0.99.3

**Comment by romeokienzler** [comment]
@Michal-Muszynski can u pse try with 0.99.0

**Comment by romeokienzler** [comment]
@Michal-Muszynski can u pse test with >= 0.99.0?

**Comment by romeokienzler** [comment]
potential solution -> tiled inference -> 'strange' output on patch/tile boundaries

@romeokienzler copy from 1st of Nov in mmseg2tt
