### ISSUE TITLE
New backbones and  decoders/heads

### ISSUE THREAD

**Issue by Joao-L-S-Almeida** [IBM/terratorch#132]
A set of backbone and decoder models must be supported in terratorch, as U-Nets and ASPP (Atrous Spatial Pyramid Pooling).

**Comment by Michal-Muszynski** [comment]
@romeokienzler we need to have a smoothly definable U-Net architecture with ASPP (Atrous Spatial Pyramid Pooling) in terratorch as our baseline for many diverse EO downstream tasks.

**Comment by romeokienzler** [comment]
@Michal-Muszynski closing as tested, please let us know if we need to reopen
