### ISSUE TITLE
Allow for multiple GPU training

### ISSUE THREAD

**Issue by romeokienzler** [IBM/terratorch#143]
**Is your feature request related to a problem? Please describe.**
Cannot use multiple GPU

**Describe the solution you'd like**
Allow for multiple GPU training

reported by @biancazadrozny

**Comment by takaomoriyama** [comment]
Testing with multi-GPU multi-node environment (CCC).
Use blaunch.sh and ddp_wrapper.py (derived from https://github.ibm.com/cognitivecomputingcluster/Distributed_Training_Examples/tree/master/pytorch_lightning)

**Comment by romeokienzler** [comment]
@takaomoriyama please create PR and add the launch script(s) to the examples folder

**Comment by takaomoriyama** [comment]
Working in https://github.com/IBM/terratorch/issues/144
