### ISSUE TITLE
cli_tools writer is not thread safe

### ISSUE THREAD

**Issue by CarlosGomes98** [IBM/terratorch#17]
https://github.com/IBM/terratorch/blob/50b909b793fe352a36367dd384f91f2411e729ba/src/terratorch/cli_tools.py#L123-L124

The code above is not "thread-safe" and may in some cases create errors. This should be an easy fix by replacing the check with `os.makedirs(exists_ok=True)`.

Thanks @Þorsteinn Elí Gíslason

**Comment by romeokienzler** [comment]
fixed in #94
