### ISSUE TITLE
Dataset/Datamodule classes for Sen4Map dataset

### ISSUE THREAD

**Issue by Foxigod** [IBM/terratorch#182]
**Is your feature request related to a problem? Please describe.**
It's been brought to my attention that there seems to be growing interest within the terratorch community of an official implementation of dataset/datamodule classes for the [Sen4Map](https://doi.org/10.1109/JSTARS.2024.3435081) dataset.

**Describe alternatives you've considered (optional)**
I've been using the Sen4Map dataset myself with terratorch, but this implementation doesn't seem to adhere to the standards placed on the dataset/datamodule classes within terratorch (e.g. inheritance/subclassing of torchgeo classes), so I don't feel confident committing my current classes.

**Comment by Joao-L-S-Almeida** [comment]
Hi, @Foxigod 
You could share your current implementation/adaptation in the form of a branch. In this way e could compare and see what should be done in order to make it compatible with the standards.

**Comment by Foxigod** [comment]
Hi @Joao-L-S-Almeida,
Does this suffice: https://github.com/Foxigod/terratorch/tree/sen4map_dataset ?

**Comment by romeokienzler** [comment]
@Foxigod pse create PR, tnx a lot!

**Comment by romeokienzler** [comment]
@Foxigod this one we can close, correct?
