### ISSUE TITLE
Example tutorial on burn scar segmentation gives error in last 2 cells of notebook

### ISSUE THREAD

**Issue by rushichavda** [IBM/terratorch#21]
### Discussed in https://github.com/IBM/terratorch/discussions/18

<div type='discussions-op-text'>

<sup>Originally posted by **rushichavda** June  7, 2024</sup>
I was going through the tutorial; everything works fine but in the second last cell, the error message says that it requires val_data and test_data.

code:
```
import os

from lightning.pytorch import Trainer
from lightning.pytorch.callbacks import EarlyStopping, LearningRateMonitor, ModelCheckpoint, RichProgressBar
from lightning.pytorch.loggers import TensorBoardLogger

accelerator = "gpu"
experiment = "tutorial"
if not os.path.isdir("tutorial_experiments"):
    os.mkdir("tutorial_experiments")
default_root_dir = os.path.join("tutorial_experiments", experiment)
checkpoint_callback = ModelCheckpoint(monitor=task.monitor, save_top_k=1, save_last=True)
early_stopping_callback = EarlyStopping(monitor=task.monitor, min_delta=0.00, patience=20)
logger = TensorBoardLogger(save_dir=default_root_dir, name=experiment)

trainer = Trainer(
    # precision="16-mixed",
    accelerator=accelerator,
    callbacks=[
        RichProgressBar(),
        checkpoint_callback,
        LearningRateMonitor(logging_interval="epoch"),
    ],
    logger=logger,
    max_epochs=epochs, # train only one epoch for demo
    default_root_dir=default_root_dir,
    log_every_n_steps=1,
    check_val_every_n_epoch=200

)
trainer.fit(model=task, datamodule=datamodule)
```
The error it gives:
![image](https://github.com/IBM/terratorch/assets/82209751/fa44ea95-4946-4523-9772-6502088d557a)

same error in the next cell:
code: 
`trainer.test(model=task, datamodule=datamodule)`

output:
![image](https://github.com/IBM/terratorch/assets/82209751/48660b4d-a313-4ff3-b8e9-99cd548197e8)

</div>

**Comment by Joao-L-S-Almeida** [comment]
Hi. At the first sight it seems your directories for validation and test are empty. Have you distributed the dataset files using some proportion as [60 %, 20 %, 20 %] for train, validation and test ? Could you provide more information about your modified configuration ?

**Comment by rushichavda** [comment]
@Joao-L-S-Almeida its an end-to-end [tutorial](https://github.com/IBM/terratorch/blob/main/examples/notebooks/Tutorial.ipynb) in the terratorch repo. given it's a tutorial, there should be everything that is required to run it from beginning to end. but if you feel that splitting dataset might solve the issue, please suggest necessary code changes...cause i am kind of new for this library. thanks

**Comment by Joao-L-S-Almeida** [comment]
Right. The notebook should create a directory `examples/notebooks/burn_scar_segmentation_toy/` and copy the same tif file for train, validation and test. Could you check if it has been properly created for your case ? My tests have worked for the same case.

**Comment by CarlosGomes98** [comment]
Marking this as stale and closing. Our own tests could not reproduce this issue. We can reopen if it persists

**Comment by rushichavda** [comment]
I think there is a requirement for test and val data. did you reproduce it on a fresh environment?
