### ISSUE TITLE
The GitHub Actions runner is suddenly interrupting the automatic tests. 

### ISSUE THREAD

**Issue by Joao-L-S-Almeida** [IBM/terratorch#221]
Actions is interrupting jobs without further information.
![image](https://github.com/user-attachments/assets/e2cf3f7d-e1ef-468e-b728-2a9883cfbacd)

Is it a time limitation ?
Maybe a memory issue ?

**Comment by romeokienzler** [comment]
1. create a parameterize(able) script to consume memory, cpu, execution time
2. slowly increase until failing

**Comment by Joao-L-S-Almeida** [comment]
I tried to increase the timeout (#232), but sometimes it is still faillling, since pytest becames inactive for a long time before starting to run.

**Comment by romeokienzler** [comment]
potentially solved in #232
