### ISSUE TITLE
Add LoRA support for fine-tuning

### ISSUE THREAD

**Issue by smandal94** [IBM/terratorch#225]
**Is your feature request related to a problem? Please describe.**
With increasing parameter sizes of pre-trained models, it has become necessary to adapt parameter efficient fine-tuning methods like LoRA, to allow people to work in constrained resource environments. 

**Describe the solution you'd like**
Add [PEFT](https://github.com/huggingface/peft) library support in configure_models() function for different tasks.

**Comment by romeokienzler** [comment]
@smandal94 creating PR (probably WIP)

**Comment by paolofraccaro** [comment]
@blumenstiel and his student have a working prototype

**Comment by smandal94** [comment]
we've decided to collaborate.

**Comment by smandal94** [comment]
#235
