### ISSUE TITLE
Custom module paths

### ISSUE THREAD

**Issue by WillTrojak** [IBM/terratorch#236]
Currently, it seems that the location of custom module is both hard coded and implied by the launch location. 

For example, a custom module has to be in a directory called `custom_modules` within the current working directory. 

For example, here:
https://github.com/IBM/terratorch/blob/9912b975ba07a0fcfb9c0d0be3c070e1b9e29cf6/terratorch/cli_tools.py#L59
https://github.com/IBM/terratorch/blob/9912b975ba07a0fcfb9c0d0be3c070e1b9e29cf6/terratorch/cli_tools.py#L390-L397
https://github.com/IBM/terratorch/blob/9912b975ba07a0fcfb9c0d0be3c070e1b9e29cf6/terratorch/registry/custom_registry.py#L6

I would suggest replacing the hard-cored paths, checking for the path in the following order of precedence:
- Command-line flag `--module-path`
- Environment variable `CUSTOM_MODULE_PATH`
- Default to the currently hard-coded path if neither is provided.

**Comment by WillTrojak** [comment]
@romeokienzler @Joao-L-S-Almeida

**Comment by romeokienzler** [comment]
thanks @WillTrojak will put it to the sprint list
