### ISSUE TITLE
Restore from local checkpoint (without any relation with HuggingFace).

### ISSUE THREAD

**Issue by Joao-L-S-Almeida** [IBM/terratorch#24]
It is necessary to include a conditional [here](https://github.com/IBM/terratorch/blob/da82a3a8e26ae715156480202f488dbbd45117a4/src/terratorch/models/prithvi_model_factory.py#L98)  in order to restore models which are not available on HuggingFace and must be loaded from a local checkpoint.

**Comment by CarlosGomes98** [comment]
@Joao-L-S-Almeida  can't this be handled by
```
backbone_pretrained_cfg_overlay:
    file: <local_path>
```
?
