### ISSUE TITLE
 cannot import name 'EncoderDecoderFactory' from 'terratorch.models'

### ISSUE THREAD

**Issue by MatthewHatami** [IBM/terratorch#243]
**Describe the issue**
I want to fine-tune Prithvi with some SAR flood images and change the decoder head so that instead of 6 bands it would accept before and after flood SAR images. To do so, I was reading the community discussions on Huggingface and came across to this note.
![image](https://github.com/user-attachments/assets/c2e4e740-b078-48ef-878e-e4f0b33550e6)
So I followed the links and got to the Quick Start page for TerraTorch. I installed the libraries and imported TerraTorch, but when I wanted to follow these codes, the highlighted line of code didn't run.
![image](https://github.com/user-attachments/assets/c1e467aa-ca25-4f2c-8f95-e320a587f934)

Then I checked the terratorch.models, and it didn't have the "EncoderDecoderFactory" which was mentioned on the codes of the website. It might have been replaced by "PrithviModelFactory" or "GenericUnetModelFactory" or any others, but the one which was mentioned on the website isn't there. So I thought bringing it up might be helpful for you =)

![image](https://github.com/user-attachments/assets/687c09e6-a648-4273-bd1d-c490acecd6dd)

**Comment by Joao-L-S-Almeida** [comment]
HI, @MatthewHatami What version are you using ? Have you installed from the main branch, from the tarballs available on GitHUb or from PyPI ?

**Comment by Joao-L-S-Almeida** [comment]
Considered solved, since it could not be replicated.
