### ISSUE TITLE
pip install shows error

### ISSUE THREAD

**Issue by romeokienzler** [IBM/terratorch#294]
**Describe the issue**
run 
pip install -e .

you get:

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
benchmark 0.1.0 requires importlib-metadata==4.13.0, but you have importlib-metadata 7.2.1 which is incompatible.

relax version requirrement on importlib-metadata
remove benchmark

reported by @paolo-fraccaro

**Comment by Joao-L-S-Almeida** [comment]
I repeated the process using the current main for python 3.11 and I didn't see that error.

**Comment by romeokienzler** [comment]
@Joao-L-S-Almeida thanks @paolo-fraccaro had an env issue, closing
