### ISSUE TITLE
Fix inverted inference results because of issues with the config files and channels while running inference

### ISSUE THREAD

**Issue by romeokienzler** [IBM/terratorch#81]

**Comment by romeokienzler** [comment]
Replicate with Michal - show to @Joao-L-S-Almeida and (@romeokienzler @biancazadrozny)

**Comment by romeokienzler** [comment]
@Michal-Muszynski can you please tell us how to replicate?

**Comment by romeokienzler** [comment]
Feedback from @Michal-Muszynski :

When we ran inference with specified input channels (following terratorch guidance), the results were inverted, but when I removed this channel part --data.init_args.predict_dataset_bands [1,2,3,4,5,6] from my command line ..., the predictions were not inverted.

https://ibm-ai-apps.slack.com/archives/C07BSEY2LAH/p1723046232648629

**Comment by romeokienzler** [comment]
@Michal-Muszynski can we close?

**Comment by Michal-Muszynski** [comment]
@romeokienzler I have tested the updated terratorch inference in the context of inverted results. Now, it seems that predictions are not inverted for almost all validation tiles.

**Comment by Michal-Muszynski** [comment]
> Feedback from @Michal-Muszynski :
> 
> When we ran inference with specified input channels (following terratorch guidance), the results were inverted, but when I removed this channel part --data.init_args.predict_dataset_bands [1,2,3,4,5,6] from my command line ..., the predictions were not inverted.
> 
> https://ibm-ai-apps.slack.com/archives/C07BSEY2LAH/p1723046232648629

That was my description of the inverted inference
