### ISSUE TITLE
Support for Regression tasks and ensure predictions are floats

### ISSUE THREAD

**Issue by romeokienzler** [IBM/terratorch#85]
Support for Regression tasks and ensure predictions are floats (previous mmseg version was predicting only integer values)

**Comment by Joao-L-S-Almeida** [comment]
A similar issue was solved in the past and it was done by including the command line argument ["out_dtype"](https://github.com/IBM/terratorch/blob/bbef2dcc8dc9a1620ede5a8490caf2e8aa05cd75/terratorch/cli_tools.py#L286), which allow the user to define the format should be used to save the output. 
The model was in fact using the proper format, but it was being [overwritten during the saving process](https://github.com/IBM/terratorch/blob/bbef2dcc8dc9a1620ede5a8490caf2e8aa05cd75/terratorch/cli_tools.py#L83).

**Comment by romeokienzler** [comment]
@Michal-Muszynski can you please test?

**Comment by Michal-Muszynski** [comment]
@romeokienzler To support regression tasks, data type selection to save predictions works well. Output predictions of fine-tuned or trained models can be saved in different data types based on requirements, for example, **integer** and **float** specified during model inference.
